import csv
import random
import string
from datetime import datetime, timedelta

# Constants
NUM_ROWS = 120000

# Utility functions
def generate_pr_id():
    length = 10 if random.random() < 0.99992 else random.randint(11, 20)
    return ''.join(random.choices(string.ascii_letters + string.digits + '-', k=length))

def generate_pr_nmn():
    allowed_chars = string.ascii_letters + string.digits + '- '
    length = random.randint(5, 15)
    return ''.join(random.choices(allowed_chars, k=length))

def generate_pr_desc():
    if random.random() < 0.00008:  # 0.008%
        tail = ''.join(random.choices(string.ascii_letters + ' ', k=random.randint(10, 80)))
        return "Generated by script " + tail
    return ""

def generate_monday_or_random_date():
    year = random.choice([2024, 2025])
    while True:
        date = datetime(year, random.randint(1, 12), random.randint(1, 28))
        if random.random() < 0.9:
            if date.weekday() == 0:  # Monday
                return date
        else:
            return date

def generate_later_date(start_date):
    while True:
        delta = timedelta(days=random.randint(1, 60))
        end_date = start_date + delta
        if random.random() < 0.8:
            if end_date.weekday() == 6:  # Sunday
                return end_date
        else:
            return end_date

def generate_app_comp_and_emp():
    if random.random() > 0.5:
        comp = random.choice([910, 920, 930])
        if comp == 930:
            emp = random.choice(list(range(30760, 30820)) + list(range(30880, 31000)))
        elif comp == 920:
            emp = random.choice(list(range(20760, 20820)) + list(range(20880, 21000)))
        elif comp == 910:
            emp = random.choice(list(range(40760, 40820)) + list(range(40880, 41000)))
        return str(comp), str(emp)
    else:
        return "", ""

def generate_pr_comp():
    return str(random.choice([910, 920, 930])) if random.random() > 0.5 else ""

# Create and write CSV
with open("final_generated_data.csv", "w", newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(["Pr_ID", "Pr_Nmn", "Pr_desc", "Pr_st", "Pr_end", "Pr_AppComp", "Pr_AppEmp", "Pr_Comp"])

    unique_ids = set()

    for _ in range(NUM_ROWS):
        while True:
            pr_id = generate_pr_id()
            if pr_id not in unique_ids:
                unique_ids.add(pr_id)
                break

        pr_nmn = generate_pr_nmn()
        pr_desc = generate_pr_desc()
        pr_st_date = generate_monday_or_random_date()
        pr_st = pr_st_date.strftime('%Y-%m-%d')

        pr_end_date = ""
        if random.random() > 0.5:
            pr_end_date = generate_later_date(pr_st_date).strftime('%Y-%m-%d')

        pr_appcomp, pr_appemp = generate_app_comp_and_emp()
        pr_comp = generate_pr_comp()

        writer.writerow([pr_id, pr_nmn, pr_desc, pr_st, pr_end_date, pr_appcomp, pr_appemp, pr_comp])

print("✅ File 'final_generated_data.csv' successfully created with 120,000 rows.")
